# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyweatherbycity',
            name='newyork_temp',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
