# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_monthlyweatherbycity_newyork_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('completed', models.IntegerField()),
            ],
        ),
    ]
