# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170516_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProjects',
            new_name='UserProject',
        ),
    ]
