# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170609_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='option_meta',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
