# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170609_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqscount',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Page'),
            preserve_default=False,
        ),
    ]
