# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_reqscount_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='project_config',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
